// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC126cHXAdyr_SOmQj493eFWqnYCBr__Is',
    appId: '1:533890652362:android:cd205aaeae384f7971fc33',
    messagingSenderId: '533890652362',
    projectId: 'starbankprojesi',
    storageBucket: 'starbankprojesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgz5BhpgvYQ3fiXwkvRFdK9Eb7L3Po76o',
    appId: '1:533890652362:ios:4340efb76e90bb4971fc33',
    messagingSenderId: '533890652362',
    projectId: 'starbankprojesi',
    storageBucket: 'starbankprojesi.firebasestorage.app',
    iosBundleId: 'com.example.starbankproject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCEDp2W6EA-L1vKw6LLJo_LmKguyaRGQ',
    appId: '1:533890652362:web:ff03ddfb82e4845271fc33',
    messagingSenderId: '533890652362',
    projectId: 'starbankprojesi',
    authDomain: 'starbankprojesi.firebaseapp.com',
    storageBucket: 'starbankprojesi.firebasestorage.app',
    measurementId: 'G-9M381PNJCX',
  );

}